os: osx
language: swift
osx_image: xcode10.1
xcode_project: PromiseU.xcodeproj
branches:
  only:
    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=PromiseU.xcodeproj
  - IOS_FRAMEWORK_SCHEME="PromiseU iOS"
  - MACOS_FRAMEWORK_SCHEME="PromiseU macOS"
  - TVOS_FRAMEWORK_SCHEME="PromiseU tvOS"
  - WATCHOS_FRAMEWORK_SCHEME="PromiseU watchOS"
  
  matrix:
    - 4.3 Apple Watch - 42mm
      - xcode_scheme: $WATCHOS_FRAMEWORK_SCHEME
      - xcode_destination: "OS=4.3,name=Apple Watch - 42mm"

    - 4.3 Apple Watch - 42mm
      - xcode_scheme: $IOS_FRAMEWORK_SCHEME
      - xcode_destination: "OS=11.3,name=iPhone X"
 
